### Create payment
POST http://localhost:8080/payments
Content-Type: application/json

{
  "amount": 99.99,
  "currency": "EUR",
  "description": "Test payment"
}

### Get payment status
GET http://localhost:8080/payments/a76120b9-c25c-49b6-8424-9fc7cbfd692c

### Get non-existing payment - should return 404
GET http://localhost:8080/payments/00000000-0000-0000

### Test validation - should return 400
POST http://localhost:8080/payments
Content-Type: application/json

{}

### Test Outbox Pattern
POST http://localhost:8080/payments
Content-Type: application/json

{
  "amount": 50.00,
  "currency": "USD",
  "description": "Outbox test"
}


### Testing payment worker

POST http://localhost:8080/payments
Content-Type: application/json

{
"amount": 99.99,
"currency": "USD",
"description": "Worker test"
}

### Testing Restart Recover

POST http://localhost:8080/payments
Content-Type: application/json

{
  "amount": 15.00,
  "currency": "USD",
  "description": "Crash recovery test"
}